name: 'ci'
on:
  push: {}
  pull_request: {}
env:
  RUST_BACKTRACE: 1
jobs:
  rustfmt:
    runs-on: 'ubuntu-18.04'
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: fmt --check 