---
name: ci
"on":
  push:
    branches:
      - master
  pull_request: {}
env:
  RUST_BACKTRACE: 1
jobs:
  rustfmt:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.40.0
          override: true
          components: "rustfmt,clippy"
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: "--check"
  clippy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.40.0
          override: true
          components: "rustfmt,clippy"
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: "-Dwarnings"